quantity = int(input("กรอกจำนวนปืนที่รับมา"))
cost_price = int(input("กรอกต้นทุนต่อกระบอก"))
sell_price = int(input("กรอกราคาที่จะขายต่อกระบอก"))
team_members = int(input("กรอกจำนวนลูกน้องในทีมที่ไปทำงาน"))

print("ต้นทุนท้งหมด "+str(quantity*cost_price)+" บาท")
print("รายได้ท้งหมด "+str(quantity*sell_price)+" บาท")
print("กำไรสุทธิ "+str((quantity*sell_price)-(quantity*cost_price))+" บาท")
print("เงินที่บอสได้รับ "+str(((quantity*sell_price)-(quantity*cost_price))*0.2)+" บาท")
print("รายได้ต่อคนของลูกน้อง "+str((((quantity*sell_price)-(quantity*cost_price))-(((quantity*sell_price)-(quantity*cost_price))*0.2))/team_members)+" บาท")